/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutEvent: typeof import('./src/components/AboutEvent.vue')['default']
    CallToAction: typeof import('./src/components/CallToAction.vue')['default']
    CounterTime: typeof import('./src/components/CounterTime.vue')['default']
    EventInfo: typeof import('./src/components/EventInfo.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NextEvents: typeof import('./src/components/NextEvents.vue')['default']
    OurPartners: typeof import('./src/components/OurPartners.vue')['default']
    OurSpeakers: typeof import('./src/components/OurSpeakers.vue')['default']
    PricingTable: typeof import('./src/components/PricingTable.vue')['default']
  }
}
